config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :employments
  get 'home/index'
  resources :employees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  has_many :employments, dependent: :destroy
  validates :first_name, presence: true, length: { minimum: 1, maximum: 25 }
  validates :last_name, presence: true, length: { minimum: 1, maximum: 50 }
  validates :phone_number, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: true }
  validates_format_of :phone_number, with: /\d{3}-\d{3}-\d{4}/,
                                     message: 'must be in the following format: xxx-xxx-xxxx'
end

app/models/employment.rb
# frozen_string_literal: true

class Employment < ApplicationRecord
  belongs_to :employee
  validates :employer, presence: true, length: { minimum: 1, maximum: 25 }
  validates :date_started, presence: true
  validates :date_employment_ended, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    partial = 'form'
    respond_to do |format|
      if @employee.save
        partial = "employments/form"
      end

      format.turbo_stream do
        render turbo_stream: turbo_stream.update(
          "employee_form",
          partial: partial,
          locals: { employee: @employee, employment: @employee&.employments&.build() }
        )
      end
    end
  end

  def update
    respond_to do |format|
      @employee.update(employee_params)
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove(
          "employee_form", 
          partial: "form",
          locals: {employee: @employee}
        )
      end
    end
  end

  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :nickname, :email, :phone_number)
    end
end

app/controllers/employments_controller.rb
# frozen_string_literal: true

class EmploymentsController < ApplicationController
  before_action :set_employment, only: %i[show edit update destroy]

  def index
    @employments = Employment.all
  end

  def show; end

  def new
    employee = Employee.find(params[:employee_id])
    @employment = employee&.employments&.build()
  end

  def edit; end

  def create
    @employment = Employment.new(employment_params)
    employees = Employee.all
    respond_to do |format|
      @employment.save
      format.turbo_stream do
        render turbo_stream: turbo_stream.update(
          'index_home',
          partial: "home/records", 
          :locals => {:@employees => employees}
        )
      end
    end
  end

  def update
    respond_to do |format|
      @employment.update(employment_params)
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          'employee_form',
          partial: 'employments/form',
          locals: { employment: @employment }
        )
      end
    end
  end

  def destroy
    @employment.destroy

    respond_to do |format|
      format.html { redirect_to employments_url, notice: 'Employment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_employment
    @employment = Employment.find(params[:id])
  end

  def employment_params
    params.require(:employment).permit(:employer, :date_started, :date_employment_ended, :employee_id)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @employees = Employee.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/employees_helper.rb
# frozen_string_literal: true

module EmployeesHelper
end

app/helpers/employments_helper.rb
# frozen_string_literal: true

module EmploymentsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/employees/_employee.html.slim
- if action_name != "show"
  |  <div id="
  = dom_id employee
  | "> 
  tr.bg-white.border-b.dark:bg-gray-800.dark:border-gray-700
    th.py-4.px-6.font-medium.text-gray-900.whitespace-nowrap.dark:text-white[scope="row"]
      = employee.first_name
    td.py-4.px-6
      = employee.last_name
    td.py-4.px-6
      = employee.email
    td.py-4.px-6
      = employee.phone_number
    td.py-4.px-6
      = employee.employments&.last&.employer
    td.py-4.px-6
      = employee.employments&.last&.date_started&.strftime("%B %d, %Y")
    td.py-4.px-6
      = employee.employments&.last&.date_employment_ended&.strftime("%B %d, %Y")
    td.py-4.px-1
      = link_to 'Add', new_employment_path({employee_id: employee.id}), "data-controller": "turbo", "data-action": "click->turbo#click", class: "bg-gray-600 rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
      = link_to 'Edit', edit_employee_path(employee), "data-controller": "turbo", class: "bg-gray-600 rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
- else
  div
    h2
      | Name: 
      = employee.first_name
      = employee.last_name
    h2
      | Email: 
      = employee.email
    h2
      | Nickname: 
      = employee.nickname
    h2
      | Phone Number: 
      = employee.phone_number
    h2
      b
        | Employment details:
    h3
      | Employer: 
      = employee.employments&.last&.employer
    h3
      | Start date: 
      = employee.employments&.last&.date_started
    h3
      | End date: 
      = employee.employments&.last&.date_employment_ended

app/views/employees/_form.html.slim
= form_with(model: employee, class: "contents") do |form|
  div[data-action="turbo:submit-end->modal#submitEnd" data-controller="validate"]
    h3.mb-4.text-xl.font-medium.text-gray-900.dark:text-white
      | Personal Information
    .my-5
      = form.label :first_name
      = form.text_field :first_name, :maxlength => 25, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", :required => true
      - if employee.errors[:first_name].any?
        ul
          - employee.errors[:first_name].each do |message|
            li.text-red-500
              | First name 
              = message
    .my-5
      = form.label :last_name
      = form.text_field :last_name, :maxlength => 50, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", :required => true
      - if employee.errors[:last_name].any?
        ul
          - employee.errors[:last_name].each do |message|
            li.text-red-500
              | Last name 
              = message
    .my-5
      = form.label :nickname
      = form.text_field :nickname, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
    .my-5.mr-2
      = form.label :email
      = form.email_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", "data-action": "change->validate#email", :required => true
      ul
        li.text-red-500
          span.error.hidden[data-validate-target="results"]
            | Email is invalid.
      - if employee.errors[:email].any?
        ul
          - employee.errors[:email].each do |message|
            li.text-red-500
              | Email 
              = message
    .my-5
      = form.label :phone_number
      = form.text_field :phone_number, :maxlength => 12, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full",  "data-action": "input->validate#phoneNumber", :required => true
      - if employee.errors[:phone_number].any?
        ul
          - employee.errors[:phone_number].each do |message|
            li.text-red-500
              | Phone number 
              = message
    .btn-holder
      .inline.mr-2[data-action="click->modal#close"]
        = link_to "Cancel", root_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
      .inline.ml-2
        = form.submit  "Save", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/employees/_form_modal.html.slim
= turbo_frame_tag "remote_modal" do
  #authentication-modal.overflow-y-auto.overflow-x-hidden.fixed.back-drop.top-0.right-0.left-0.z-50.w-full.md:inset-0.h-modal.md:h-full.justify-center.items-center.flex[data-controller="modal" tabindex="-1" aria-modal="true" role="dialog"]
    .relative.p-4.w-full.max-w-md.h-full
      .hidden.relative.bg-white.rounded-lg.shadow.dark:bg-gray-700[data-modal-target="display"]
        button.absolute.top-3.right-2.5.text-gray-400.bg-transparent.hover:bg-gray-200.hover:text-gray-900.rounded-lg.text-sm.p-1.5.ml-auto.inline-flex.items-center.dark:hover:bg-gray-800.dark:hover:text-white[type="button" data-modal-toggle="authentication-modal"]
          svg.w-5.h-5[data-action="click->modal#close" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"]
            path[fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"]
          span.sr-only[data-action="click->modal#close"]
            | Close modal
        .py-6.px-6.lg:px-8
          = turbo_frame_tag "employee_form" do
            = render "form", employee: @employee

app/views/employees/edit.html.slim
.mx-auto.md:w-2/3.w-full
  h1.font-bold.text-4xl
    | Editing employee
  = render "form", employee: @employee
  = link_to "Show this employee", @employee, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to "Back to employees", employees_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/employees/edit.turbo_stream.slim
= turbo_stream.replace "remote_modal" do
  = render partial: "form_modal", local: {project: @project}

app/views/employees/index.html.slim
.w-full
  - if notice.present?
    p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block
      = notice
  .flex.justify-between.items-center
    h1.font-bold.text-4xl
      | Employees
    = link_to "Back to Home Page", root_path, class: "mb-1 ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = turbo_frame_tag "refresh_content", target: :_top do
    #employees.container.mx-auto.px-5
      .overflow-x-auto.relative
        table.w-full.text-sm.text-left.text-gray-500.dark:text-gray-400
          thead.border-b.text-xs.text-gray-700.uppercase.bg-gray-50.dark:bg-gray-700.dark:text-gray-400
            tr
              th.py-3.px-6[scope="col"]
                |  First Name 
              th.py-3.px-6[scope="col"]
                |  Last Name 
              th.py-3.px-6[scope="col"]
                |  Email 
              th.py-3.px-6[scope="col"]
                |  Phone Number 
              th.py-3.px-6[scope="col"]
                |  Employer
              th.py-3.px-6[scope="col"]
                |  Start date
              th.py-3.px-6[scope="col"]
                |  Employment end date
              th.py-3.px-6[scope="col"]
                |  Action 
          tbody
            = render @employees

app/views/employees/new.html.slim
.mx-auto.md:w-2/3.w-full
  h1.font-bold.text-4xl
    | New employee
  = render "form", employee: @employee
  = link_to 'Back to employees', employees_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/employees/new.turbo_stream.slim
= turbo_stream.replace "remote_modal" do
  = render partial: "form_modal", local: {employee: @employee}

app/views/employees/show.html.slim
.mx-auto.md:w-2/3.w-full.flex
  .mx-auto
    - if notice.present?
      p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block
        = notice
    = render @employee
    .flex.justify-center
      .inline-block.ml-2
        = button_to 'Destroy this employee', employee_path(@employee), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
      = link_to 'Back to employees', employees_path, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 ml-2 font-medium"

app/views/employments/_employment.html.slim
| <div id="
= dom_id employment
| "> 
p.my-5
  strong.block.font-medium.mb-1
    | Employer:
  = employment.employer
p.my-5
  strong.block.font-medium.mb-1
    | Date started:
  = employment.date_started
p.my-5
  strong.block.font-medium.mb-1
    | Date employment ended:
  = employment.date_employment_ended
- if action_name != "show"
  = link_to "Show this employment", employment, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to 'Edit this employment', edit_employment_path(employment), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
  hr.mt-6

app/views/employments/_form.html.slim
= turbo_frame_tag "employee_form", target: :_top do
  div[data-action="turbo:submit-end->modal#submitEnd"]
    h3.mb-4.text-xl.font-medium.text-gray-900.dark:text-white
      | Employer Information
    = form_with(model: employment, class: "contents") do |form|
      - if employment.errors.any?
        #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
          h2
            = pluralize(employment.errors.count, "error")
            |  prohibited this employment from being saved:
          ul
            - employment.errors.each do |error|
              li
                = error.full_message
      .my-5
        = form.label :employer
        = form.text_field :employer, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", :required => true
      .my-5
        = form.label :date_started
        = form.date_field :date_started, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", :required => true
      .my-5
        = form.label :date_employment_ended
        = form.date_field :date_employment_ended, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", :required => true
      .my-5
        = form.hidden_field :employee_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
      .btn-holder
        .inline
          = form.submit "Save", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/employments/_form_modal.html.slim
= turbo_frame_tag "remote_modal" do
  #authentication-modal.overflow-y-auto.overflow-x-hidden.fixed.back-drop.top-0.right-0.left-0.z-50.w-full.md:inset-0.h-modal.md:h-full.justify-center.items-center.flex[data-controller="modal" tabindex="-1" aria-modal="true" role="dialog"]
    .relative.p-4.w-full.max-w-md.h-full
      .hidden.relative.bg-white.rounded-lg.shadow.dark:bg-gray-700[data-modal-target="display"]
        button.absolute.top-3.right-2.5.text-gray-400.bg-transparent.hover:bg-gray-200.hover:text-gray-900.rounded-lg.text-sm.p-1.5.ml-auto.inline-flex.items-center.dark:hover:bg-gray-800.dark:hover:text-white[type="button" data-modal-toggle="authentication-modal"]
          svg.w-5.h-5[data-action="click->modal#close" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"]
            path[fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"]
          span.sr-only[data-action="click->modal#close"]
            | Close modal
        .py-6.px-6.lg:px-8
          = turbo_frame_tag "employee_form" do
            = render "form", employment: @employment

app/views/employments/edit.html.slim
.mx-auto.md:w-2/3.w-full
  h1.font-bold.text-4xl
    | Editing employment
  = render "form", employment: @employment
  = link_to "Show this employment", @employment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to "Back to employments", employments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/employments/index.html.slim
.w-full
  - if notice.present?
    p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block
      = notice
  .flex.justify-between.items-center
    h1.font-bold.text-4xl
      | Employments
    = link_to 'New employment', new_employment_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"
  #employments.min-w-full
    = render @employments

app/views/employments/new.html.slim
.mx-auto.md:w-2/3.w-full
  h1.font-bold.text-4xl
    | New employment
  = render "form", employment: @employment
  = link_to 'Back to employments', employments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/employments/new.turbo_stream.slim
= turbo_stream.replace "remote_modal" do
  = render partial: "form_modal", local: {employment: @employment}

app/views/employments/show.html.slim
.mx-auto.md:w-2/3.w-full.flex
  .mx-auto
    - if notice.present?
      p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block
        = notice
    = render @employment
    = link_to 'Edit this employment', edit_employment_path(@employment), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    .inline-block.ml-2
      = button_to 'Destroy this employment', employment_path(@employment), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
    = link_to 'Back to employments', employments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/home/_records.html.slim
.w-full.flex.justify-center
  - if notice.present?
    p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block
      = notice
table.w-full.text-sm.text-left.text-gray-500.dark:text-gray-400
  thead.border-b.text-xs.text-gray-700.uppercase.bg-gray-50.dark:bg-gray-700.dark:text-gray-400
    tr
      th.py-3.px-6[scope="col"]
        |  First Name 
      th.py-3.px-6[scope="col"]
        |  Last Name 
      th.py-3.px-6[scope="col"]
        |  Email 
      th.py-3.px-6[scope="col"]
        |  Phone Number 
      th.py-3.px-6[scope="col"]
        |  Employer
      th.py-3.px-6[scope="col"]
        |  Start date
      th.py-3.px-6[scope="col"]
        |  Employment end date
      th.py-3.px-6[scope="col"]
        |  Action 
  tbody
    = render @employees

app/views/home/index.html.slim
= turbo_frame_tag "index_home" do
  = render partial: "home/records", :locals => {:@employees => @employees}

app/views/layouts/_header.html.slim
nav.p-3.rounded.border-gray-200.dark:bg-gray-800.dark:border-gray-700
  .container.flex.flex-wrap.justify-between.items-center.mx-auto.p-4
    a.flex.items-center href="#" 
      img.mr-3.h-6.sm:h-10 alt=("Rails Stimulus") src="https://flowbite.com/docs/images/logo.svg" /
      span.self-center.text-xl.font-semibold.whitespace-nowrap.dark:text-white Rails Stimulus
    #navbar-solid-bg.md:block.md:w-auto
      ul.flex.flex-col.mt-4.bg-gray-50.rounded-lg.md:flex-row.md:space-x-8.md:mt-0.md:text-sm.md:font-medium.md:border-0.md:bg-transparent.dark:bg-gray-800.md:dark:bg-transparent.dark:border-gray-700
        li.mr-2
          a.flex.block.py-2.pr-4.pl-3.rounded.hover:bg-gray-100.md:hover:bg-transparent.md:border-0.md:hover:text-blue-700.md:p-0.dark:text-gray-400.md:dark:hover:text-white.dark:hover:bg-gray-700.dark:hover:text-white.md:dark:hover:bg-transparen.mr-2[data-controller="turbo" href="/employees/new" data-action="click->turbo#click"]
            svg.h-5.inline[xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke="currentColor" stroke-width="2"]
              path[stroke-linecap="round" stroke-linejoin="round" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"]
            | Personal Data

         
        

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Rails Stimulus
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    = render partial: 'layouts/header'
    main.container.mx-auto.mt-28.px-5
      = yield
      = turbo_frame_tag "remote_modal"